language: go
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - master
os:
  - linux
env:
  - GO111MODULE=on
#  - GOFLAGS=-mod=vendor
install: true

script:
  - make test
  - make build
  - ./bin/wotreplay-parse -version
