language: go

go:
  - 1.x
  - master

before_script:
  - make govendor
  - mkdir -p $HOME/.wine/drive_c/Games/World_of_Tanks/replays

script:
  - make test
  - make build
  - ./bin/wotreplay-parse -version
